# Generated by Django 4.1 on 2024-06-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0002_alter_financialyear_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteSaleDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=50, null=True)),
                ("password", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
