# Generated by Django 4.1 on 2024-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0004_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Licenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("license_type", models.CharField(max_length=10, null=True)),
                ("expiry_remainder", models.CharField(max_length=10, null=True)),
                ("expiry_date", models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
