# Generated by Django 4.1 on 2024-06-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0005_licenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenses",
            name="licenseFile",
            field=models.FileField(blank=True, null=True, upload_to="licenses/"),
        ),
    ]
