# Generated by Django 4.1 on 2024-06-06 04:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0006_licenses_licensefile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="licenses",
            old_name="license_type",
            new_name="license_name",
        ),
    ]
