# Generated by Django 4.1 on 2024-06-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0007_rename_license_type_licenses_license_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenses",
            name="license_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
