# Generated by Django 4.1 on 2024-06-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0008_alter_licenses_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenses",
            name="expiry_remainder",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
