# Generated by Django 4.1 on 2024-06-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0013_bank"),
    ]

    operations = [
        migrations.CreateModel(
            name="HSNCodeTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hs_code", models.CharField(max_length=15, null=True)),
                ("description", models.CharField(max_length=255, null=True)),
                ("goods_service", models.CharField(max_length=10, null=True)),
                (
                    "igst",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "sgst",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "cgst",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "cess",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "compensation_cess",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "flood_cess",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
            ],
        ),
    ]
