# Generated by Django 4.1 on 2024-06-10 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0014_hsncodetax"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HSNCodeTax",
            new_name="taxmaster",
        ),
    ]
