# Generated by Django 4.1 on 2024-06-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0015_rename_hsncodetax_taxmaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
            ],
        ),
    ]
