# Generated by Django 4.1 on 2024-06-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0017_vendordetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("blood_group", models.CharField(blank=True, max_length=10, null=True)),
                ("designation", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=350)),
                ("phone", models.CharField(max_length=20)),
                ("phone_2", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(max_length=255)),
                ("doj", models.DateField()),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ac_number", models.CharField(max_length=255)),
                ("govt_id", models.CharField(max_length=255)),
            ],
        ),
    ]
