# Generated by Django 4.1 on 2024-06-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0019_employee_emp_type_alter_employee_employee_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Member_PHOTO",
                    models.ImageField(blank=True, null=True, upload_to="memberphoto/"),
                ),
                ("Member_TYPE", models.CharField(max_length=50, null=True)),
                ("Member_ID", models.CharField(max_length=50, null=True)),
                ("Member_NAME", models.CharField(max_length=50, null=True)),
                ("Member_ADDRESS", models.CharField(max_length=50, null=True)),
                ("Member_PHONE_NNUMBER", models.CharField(max_length=255)),
                ("Member_EMAIL", models.EmailField(max_length=255)),
                ("Member_ADHAR_NO", models.CharField(max_length=50, null=True)),
                ("Member_GST", models.CharField(max_length=50, null=True)),
                ("Member_DATE_OF_JOINING", models.CharField(max_length=10, null=True)),
                ("Member_OPENING_BALENCE", models.CharField(max_length=50, null=True)),
                ("Member_CURRENT_BALANCE", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "employee_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="venadapp.employee",
                    ),
                ),
            ],
        ),
    ]
