# Generated by Django 4.1 on 2024-06-13 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0020_member_attendance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="employee_name",
            new_name="x",
        ),
    ]
