# Generated by Django 4.1 on 2024-06-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0021_rename_employee_name_attendance_x"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="x",
            new_name="employee",
        ),
        migrations.AddField(
            model_name="attendance",
            name="attendance",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
