# Generated by Django 4.1 on 2024-06-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0022_rename_x_attendance_employee_attendance_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_category", models.CharField(max_length=20)),
                ("product_type", models.CharField(max_length=255, null=True)),
                ("product_code", models.CharField(max_length=20, null=True)),
                ("product_name", models.CharField(max_length=50, null=True)),
                ("product_unit", models.CharField(max_length=50, null=True)),
                ("hsn_code_description", models.CharField(max_length=50, null=True)),
                ("hsn_code", models.CharField(max_length=50, null=True)),
                ("opening_stoct", models.CharField(max_length=50, null=True)),
                ("minimum_stock", models.CharField(max_length=50, null=True)),
                ("r1price", models.CharField(max_length=50, null=True)),
                ("r2price", models.CharField(max_length=50, null=True)),
                ("r3price", models.CharField(max_length=50, null=True)),
                ("description", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
