# Generated by Django 4.1 on 2024-06-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0025_rename_balence_adv_payment_remainingbalence"),
    ]

    operations = [
        migrations.AddField(
            model_name="adv_payment",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="venadapp.employee",
            ),
        ),
    ]
