# Generated by Django 4.1 on 2024-06-20 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0026_adv_payment_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="hsn_code",
        ),
        migrations.AlterField(
            model_name="products",
            name="hsn_code_description",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="venadapp.taxmaster",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="product_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="venadapp.productcategory",
            ),
        ),
    ]
