# Generated by Django 4.1 on 2024-07-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0027_remove_products_hsn_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Overtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("amount", models.CharField(max_length=50, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="venadapp.employee",
                    ),
                ),
            ],
        ),
    ]
