# Generated by Django 4.1 on 2024-07-08 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("venadapp", "0028_overtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_no", models.BigIntegerField(max_length=50, null=True)),
                ("ref_no", models.BigIntegerField(max_length=50, null=True)),
                ("purchase_date", models.CharField(max_length=50, null=True)),
                ("reciept_date", models.CharField(max_length=50, null=True)),
                ("mop", models.CharField(max_length=50, null=True)),
                ("tax_mode", models.CharField(max_length=50, null=True)),
                ("gross_amount", models.BigIntegerField(max_length=50, null=True)),
                ("purchase_tax", models.BigIntegerField(max_length=50, null=True)),
                ("taxable_amount", models.BigIntegerField(max_length=50, null=True)),
                ("paid_amount", models.BigIntegerField(max_length=50, null=True)),
                ("total_discount", models.BigIntegerField(max_length=50, null=True)),
                ("qty_total", models.BigIntegerField(max_length=50, null=True)),
                ("old_balalnce", models.BigIntegerField(max_length=50, null=True)),
                ("total_amount", models.BigIntegerField(max_length=50, null=True)),
                ("new_balance", models.BigIntegerField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="purchased_products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.CharField(max_length=50, null=True)),
                ("unit", models.CharField(max_length=50, null=True)),
                ("prate", models.CharField(max_length=50, null=True)),
                ("MRP", models.CharField(max_length=50, null=True)),
                ("discount", models.CharField(max_length=50, null=True)),
                ("amount", models.CharField(max_length=50, null=True)),
                ("taxable_amount", models.CharField(max_length=50, null=True)),
                ("cgst_amount", models.CharField(max_length=50, null=True)),
                ("sgst_amount", models.CharField(max_length=50, null=True)),
                ("igst_amount", models.CharField(max_length=50, null=True)),
                ("net_amount", models.CharField(max_length=50, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="venadapp.products",
                    ),
                ),
                (
                    "purchased_prod",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="venadapp.purchasedetails",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="venadapp.vendordetails",
                    ),
                ),
            ],
        ),
    ]
