from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns =[
    path("",views.home),
    path("login/",views.checklogin),
    path("dashboard/",views.dashboard),
    path("financialyear/",views.financialyear),
    path("financialyearadd/",views.financialyearadd),
    path("financialyearedit/", views.financialyearedit),
    path("financialyearadd/",views.financialyearadd_tbl),
    path("savefinancialyear/",views.savefinancialyear),
    path("delrow/<id>",views.delete_row),
    path("route/",views.routsale),
    path("routeadd/",views.routsale_add),
    path("routetbl/", views.routesaleadd_tbl),
    path("routeedit/",views.routesale_edit),
    path("saveroutesale/", views.saveroutesale),
    path("delrowroute/<id>",views.delete_row_route),
    path("changepassword/",views.changepassword),
    path("reset_password/",views.reset_password),
    path("companydetails/",views.basicinformation),
    path("update_company/", views.update_company),
    path("update_company_view/", views.update_company_view),
    path("licenses/", views.licenses),
    path('licensesadd/', views.licensesaddview),
    path("licensesedit/", views.licensesedit),
    path("delrowlicenses/<id>",views.delete_row_licenses),
    path("savelicenses/", views.savelicences),
    path('licenses_add/',views.licenses_add),
    path("shareholdershome/",views.shareholdershome),
    path("addshareholder/",views.addshareholder),
    path("editshareholder/<id>",views.editshareholder),
    path('edit_submit_shareholder/', views.edit_submit_shareholder),
    path('submit_shareholder/', views.submit_shareholder),
    path("delshareholder/<id>",views.delshareholder),
    path("dir_det/",views.directordetails),
    path("dir_add/",views.director_det_add),
    path("dir_det_add/",views.director_details_add),
    path("dir_del/<id>",views.director_del),
    path("dir_edit/",views.director_edit),
    path("dir_edit_save/",views.savedirDet),
    path("licensesprint/",views.licensesprint),
    path("bank_add/", views.bankadd_tbl),
    path('bankadd/', views.add_bank),
    path("delbank1/<id>", views.deletebank),
    # path("delbank/<id>",views.delete_bank),
    path("editbank/", views.bank_edit),
    path("savebankedit/", views.save_bank),
    path('bank/',views.bank_page),
    path('bankadd/', views.bankadd_page),
    path('taxmaster/', views.taxmaster_list),
    path('taxmasteraddpage/', views.taxmasteraddview),
    path('taxmasteradd/', views.add_taxmaster),
    path('taxmasteredit/<id>/', views.edit_taxmaster),
    path('deltaxmaster/<id>/', views.delete_taxmaster),
    path('savetaxmasteredit/', views.save_taxmaster),
    path("productcategory/", views.productcategory),
    path("addcategory/", views.addcategory),
    path("savecategory/", views.savecategory),
    path("editcategory/<id>",views.editcategory),
    path("deletecategory/<id>",views.deletecategory),
    path("v_det_page/",views.vendor_details_page),
    path("v_edit_page/",views.vendor_edit_page),
    path("v_add_page/",views.vendor_add_page),
    path("vendor_add/",views.vendor_add_tbl),
    path("vendor_del/<id>",views.vendor_delete),
    path('vendor_edit/',views.vendor_edit),
    path("employeemaster/", views.employeemaster),
    path('employeemasteradd/', views.employeemasteraddview),
    path("add_employee/",views.add_employee),
    path("del_employee/<id>",views.delete_employee),
    path("edit_employee/<id>",views.employee_edit_page),
    path("save_edit_employee/",views.employee_edit_save),
    path("Attendance_Register/",views.Attendance_Registerview),
    path("members_page/",views.members_page),
    path("add_members_page/",views.members_add_page),
    path("add_members/",views.members_add),
    path("member_edit_page/<id>",views.member_edit_page),
    path("member_del_page/<id>",views.member_del_page),
    path("employeemaster/", views.employeemaster),
    path("mark_attendance/<id>",views.mark_attendance),
    path("save_attendance/<id>",views.save_attendance),
    path("product/",views.product),
    path("add_product/",views.prodAdd),
    path("product_add/",views.product_add),
    path("save_product_edit/",views.save_product_edit),
    path("product_edit/<id>",views.product_edit_page),
    path("product_del/<id>",views.product_del_tbl),
    path("advance_payment/", views.advpayment_view),
    path("advance_payment_add/", views.advance_paymentadd),
    path('your-url/', views.ajax_view),
    path("save_advance_payment/",views.save_advancepayment),
    path("advpayedit/", views.advpayedit),
    path("deladv/<id>", views.deladv),
    path("advance_payment/", views.advpayment_view),
    path("take_hsn_code/",views.take_hsn_code,name="take_hsn_code"),
    path("Overtime_details/",views.overtime_details),
    path("overtimeadd/",views.overtime_add),
    path("overtime_save/",views.overtime_save),
    path("overtime_edit_page/<id>",views.overtime_edit_page),
    path("delete_overtime/<id>",views.overtime_delete),
    path('overtime_edit_save/',views.overtime_edit_save),
    path("purchase_det_page/",views.purchase_details_page),
    path("purchase_add_page/",views.purchase_add_page),
    path('add_purchase/', views.purchase_add_save),
    path('your-url_products/', views.ajax_view_for_products),
    path('invoice/<id>',views.invoice_page),
    path('purchase_edit/',views.purchase_edit_save),
    path('del_pur_row/<id>',views.del_pur_row),
    path('your-url/', views.ajax_view),
    path('del_purchase/<id>',views.purchase_delete),
    path('edit_purchase/<id>',views.purchase_edit),
    path("sale_home/",views.salehome),
    path("addsale/",views.addsale),
    path('get_customers/', views.get_customers, name='get_customers'),
    path('get-product-details/', views.get_product_details, name='get_product_details'),
    path("savesale/",views.save_sale),
    path('invoice/<id>',views.invoice),
    path('deletesale/<id>',views.delete_sale),
    path('getOldBalance/', views.get_old_balance, name='get_old_balance'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
